dataset:
  train: train.parquet
  test: test.parquet

training:
  features: [
    # Raw features
    cfips,
    # Census starter features
    #pct_bb_2017, pct_bb_2018, pct_bb_2019, pct_bb_2020, pct_bb_2021,
    #pct_college_2017, pct_college_2018, pct_college_2019, pct_college_2020, pct_college_2021,
    # Lag features
    microbusiness_density_shift_5, microbusiness_density_shift_6, microbusiness_density_shift_7,
    microbusiness_density_shift_8, microbusiness_density_shift_9, microbusiness_density_shift_10,
    microbusiness_density_shift_11, microbusiness_density_shift_12
    #microbusiness_density_shift_5_diff_1, microbusiness_density_shift_5_pct_change_1,



  ]
  target: microbusiness_density
  categorical_features: [
  ]
  folds: [
    fold1
    #fold1, fold2, fold3, fold4,
    #fold5, fold6, fold7, fold8
  ]

model:
  num_leaves: 128
  learning_rate: 0.1
  bagging_fraction: 0.9
  bagging_freq: 1
  feature_fraction: 0.8
  feature_fraction_bynode: 1
  min_data_in_leaf: 20
  min_gain_to_split: 0.00001
  lambda_l1: 0.
  lambda_l2: 0.
  max_bin: 255
  max_depth: -1
  boost_from_average: True
  objective: regression_l1
  seed: 42
  feature_fraction_seed: 42
  bagging_seed: 42
  drop_seed: 42
  data_random_seed: 42
  boosting_type: gbdt
  verbose: 1
  n_jobs: -1

fit:
  boosting_rounds: 10000
  early_stopping: 200
  log_evaluation: 200

persistence:
  save_models: True
  visualize_scores: True
  visualize_val_predictions: False
  visualize_feature_importance: True