dataset:
  train: train.parquet
  test: test.parquet

training:
  features: [
    # Raw features
    cfips,
    # Lag features
    microbusiness_density_shift_5, active_shift_5,
    microbusiness_density_shift_6, active_shift_6,
    microbusiness_density_shift_7, active_shift_7,
    microbusiness_density_shift_8, active_shift_8,
    microbusiness_density_shift_9, active_shift_9,
    microbusiness_density_shift_10, active_shift_10,
    county_orders_rank_shift_5, county_merchants_rank_shift_5,
    county_gmv_rank_shift_5, county_total_pop_20_shift_5,

    # Diff features
    microbusiness_density_shift_5_diff_1, active_shift_5_diff_1,

  ]
  target: microbusiness_density
  categorical_features: [
  ]
  folds: [
    #fold8
    #fold1, fold2, fold3, fold4,
    #fold5, fold6, fold7, fold8,
    #fold9, fold10, fold11
    fold11
  ]

model:
  num_leaves: 128
  learning_rate: 0.01
  bagging_fraction: 0.9
  bagging_freq: 1
  feature_fraction: 0.9
  feature_fraction_bynode: 1
  min_data_in_leaf: 20
  min_gain_to_split: 0.00001
  lambda_l1: 0.
  lambda_l2: 0
  max_bin: 512
  max_depth: -1
  boost_from_average: True
  objective: regression_l1
  #metric: None
  seed: 42
  feature_fraction_seed: 42
  bagging_seed: 42
  drop_seed: 42
  data_random_seed: 42
  boosting_type: gbdt
  verbose: 1
  n_jobs: -1

fit:
  boosting_rounds: 10000
  early_stopping: 200
  log_evaluation: 200

persistence:
  save_models: True
  visualize_scores: True
  visualize_val_predictions: False
  visualize_feature_importance: True