dataset:
  train: train.parquet
  test: test.parquet

training:
  target: microbusiness_density
  folds: [
    fold1, fold2, fold3, fold4,
    fold5, fold6, fold7, fold8
  ]

persistence:
  visualize_scores: True
  visualize_val_predictions: False
  visualize_test_predictions: False
